stages:
  split_subsets:
    cmd: python dataset_splitter.py --dataset-path data/external/defects/train --output-dataset-path data/processed/defects/
    deps:
      - dataset_splitter.py
      - data/external/defects/train
    outs:
      - data/processed/defects

  train_model:
    cmd: python train.py --dataset-path data/processed/defects --device cuda --batch-size 16 --img-size 32 --num-epochs 15 --project-name mnad
    deps:
      - train.py
      - data/processed/defects
    outs:
      - models

  select_threshold:
    cmd: python threshold_selector.py --dataset-path data/external/defects/proliv --img-size 32 --checkpoint-path models/model.ckpt
    deps:
      - threshold_selector.py
      - data/external/defects/proliv
      - models/model.ckpt


  test_model:
    cmd: python test.py --dataset-path data/external/defects/test --img-size 32 --project-name mnad --checkpoint-path models/model.ckpt
    deps:
      - test.py
      - models/model.ckpt
      - data/external/defects/test
